"""migracija_po_isvalymo

Revision ID: ba6d00ecb983
Revises: 
Create Date: 2025-03-11 21:51:18.782871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6d00ecb983'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamentas',
    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
    sa.Column('pavadinimas', sa.String(50), nullable=False),
    sa.Column('vadovas_id', sa.Integer(), nullable=True),
    )

    # Tada sukuriame DARBUOTOJAS
    op.create_table('darbuotojas',
    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
    sa.Column('vardas', sa.String(50), nullable=False),
    sa.Column('pavarde', sa.String(50), nullable=False),
    sa.Column('gimimo_data', sa.Date()),
    sa.Column('pareigos', sa.String(40), nullable=False),
    sa.Column('atlyginimas', sa.Integer()),
    sa.Column('pradzios_data', sa.DateTime(), server_default=sa.func.current_timestamp()),
    sa.Column('departamentas_id', sa.Integer(), nullable=True),
    )

    # Galiausiai PRIDEDAME FOREIGN KEY PO ABIJŲ LENTELIŲ SUKŪRIMO
    op.create_foreign_key('fk_darbuotojas_departamentas', 'darbuotojas', 'departamentas', ['departamentas_id'], ['id'], ondelete="SET NULL")
    op.create_foreign_key('fk_departamentas_vadovas', 'departamentas', 'darbuotojas', ['vadovas_id'], ['id'], ondelete="SET NULL")
    
    op.create_table('projektas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pavadinimas', sa.String(length=50), nullable=False),
    sa.Column('aprasymas', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('darbuotojas_projektas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('darbuotojas_id', sa.Integer(), nullable=False),
    sa.Column('projektas_id', sa.Integer(), nullable=False),
    sa.Column('role_projekte', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['darbuotojas_id'], ['darbuotojas.id'], ),
    sa.ForeignKeyConstraint(['projektas_id'], ['projektas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('darbuotojas_projektas')
    op.drop_table('projektas')
    op.drop_table('departamentas')
    op.drop_table('darbuotojas')
    # ### end Alembic commands ###
